last_change = 2024-07-12T04:40:01.450351Z
addr = 0xb04780
size = 0x72e
name = "_ZN9CSprite2d4DrawEffffffffRK5CRGBA"

[header]
last_change = 2024-07-12T04:26:23.282208Z
name = "_ZN9CSprite2d4DrawEffffffffRK5CRGBA"
addr = 0xb04780

[header.args]

[stack_vars.-0x28]
last_change = 2024-07-12T04:40:01.444350Z
offset = -40
name = "a5"
type = "int"
size = 0x4
addr = 0xb04780

[stack_vars.-0x20]
last_change = 2024-07-12T04:40:01.445350Z
offset = -32
name = "a6"
type = "float"
size = 0x4
addr = 0xb04780

[stack_vars.-0x18]
last_change = 2024-07-12T04:40:01.446350Z
offset = -24
name = "a7"
type = "char"
size = 0x1
addr = 0xb04780

[stack_vars.-0x10]
last_change = 2024-07-12T04:40:01.448351Z
offset = -16
name = "a8"
type = "char"
size = 0x1
addr = 0xb04780

[stack_vars.-0x8]
last_change = 2024-07-12T04:40:01.449351Z
offset = -8
name = "a9"
type = "long long"
size = 0x8
addr = 0xb04780

[stack_vars.0x0]
last_change = 2024-07-12T04:40:01.450351Z
offset = 0x0
name = "a10"
type = "long long"
size = 0x8
addr = 0xb04780
