last_change = 2024-07-13T02:26:11.262344Z
addr = 0x10758a0
size = 0x9f8

[stack_vars.-0x238]
last_change = 2024-07-13T02:26:11.262344Z
offset = -568
name = "m"
type = "CMatrix"
size = 0x50
addr = 0x10758a0
