last_change = 2024-07-12T20:38:27.643006Z
addr = 0x109b250
size = 0x6c4

[stack_vars.-0x138]
last_change = 2024-07-12T20:38:27.643006Z
offset = -312
name = "var_110"
type = "long long"
size = 0x8
addr = 0x109b250
