last_change = 2024-07-12T16:10:01.567512Z
addr = 0x10e6e80
size = 0x216
name = "_ZN5CFont11PrintStringEffPh"

[header]
last_change = 2024-07-12T16:00:41.999598Z
name = "_ZN5CFont11PrintStringEffPh"
addr = 0x10e6e80

[header.args]

[stack_vars.-0x60]
last_change = 2024-07-12T16:10:01.567512Z
offset = -96
name = "coords"
type = "float"
size = 0x4
addr = 0x10e6e80

[stack_vars.0x0]
last_change = 2024-07-12T16:09:41.978141Z
offset = 0x0
name = "arg_10"
type = "CRGBA"
size = 0x4
addr = 0x10e6e80

[stack_vars.-0x5c]
last_change = 2024-07-12T16:08:30.606312Z
offset = -92
name = "var_44"
type = "CRect"
size = 0x10
addr = 0x10e6e80

[stack_vars.-0x58]
last_change = 2024-07-12T16:08:37.376322Z
offset = -88
name = "var_40"
type = "CRect"
size = 0x10
addr = 0x10e6e80
