last_change = 2024-07-12T20:42:16.409390Z
addr = 0x1230680
size = 0x3a9
name = "_ZN6CTrain25ReadAndInterpretTrackFileEPcPP10CTrainNodePiPfi"

[header]
last_change = 2024-07-12T20:40:54.531725Z
name = "_ZN6CTrain25ReadAndInterpretTrackFileEPcPP10CTrainNodePiPfi"
addr = 0x1230680

[header.args]

[stack_vars.0x0]
last_change = 2024-07-12T20:42:16.409390Z
offset = 0x0
name = "skipStations"
type = "int"
size = 0x4
addr = 0x1230680
