last_change = 2024-07-12T20:38:14.801575Z
addr = 0x124fae0
size = 0x62d

[stack_vars.-0x100]
last_change = 2024-07-12T20:38:14.801575Z
offset = -256
name = "z"
type = "float"
size = 0x4
addr = 0x124fae0
