[eRadarSprite]
last_change = 2024-07-12T04:23:40.426454Z
name = "eRadarSprite"

[eRadarSprite.members]
RADAR_SPRITE_NONE = 0x0
RADAR_SPRITE_WHITE = 0x1
RADAR_SPRITE_CENTRE = 0x2
RADAR_SPRITE_MAP_HERE = 0x3
RADAR_SPRITE_NORTH = 0x4
RADAR_SPRITE_AIRYARD = 0x5
RADAR_SPRITE_AMMUGUN = 0x6
RADAR_SPRITE_BARBERS = 0x7
RADAR_SPRITE_BIGSMOKE = 0x8
RADAR_SPRITE_BOATYARD = 0x9
RADAR_SPRITE_BURGERSHOT = 0xa
RADAR_SPRITE_BULLDOZER = 0xb
RADAR_SPRITE_CATALINAPINK = 0xc
RADAR_SPRITE_CESARVIAPANDO = 0xd
RADAR_SPRITE_CHICKEN = 0xe
RADAR_SPRITE_CJ = 0xf
RADAR_SPRITE_CRASH1 = 0x10
RADAR_SPRITE_DINER = 0x11
RADAR_SPRITE_EMMETGUN = 0x12
RADAR_SPRITE_ENEMYATTACK = 0x13
RADAR_SPRITE_FIRE = 0x14
RADAR_SPRITE_GIRLFRIEND = 0x15
RADAR_SPRITE_HOSTPITAL = 0x16
RADAR_SPRITE_LOGOSYNDICATE = 0x17
RADAR_SPRITE_MADDOG = 0x18
RADAR_SPRITE_MAFIACASINO = 0x19
RADAR_SPRITE_MCSTRAP = 0x1a
RADAR_SPRITE_MODGARAGE = 0x1b
RADAR_SPRITE_OGLOC = 0x1c
RADAR_SPRITE_PIZZA = 0x1d
RADAR_SPRITE_POLICE = 0x1e
RADAR_SPRITE_PROPERTYG = 0x1f
RADAR_SPRITE_PROPERTYR = 0x20
RADAR_SPRITE_RACE = 0x21
RADAR_SPRITE_RYDER = 0x22
RADAR_SPRITE_SAVEGAME = 0x23
RADAR_SPRITE_SCHOOL = 0x24
RADAR_SPRITE_QMARK = 0x25
RADAR_SPRITE_SWEET = 0x26
RADAR_SPRITE_TATTOO = 0x27
RADAR_SPRITE_THETRUTH = 0x28
RADAR_SPRITE_WAYPOINT = 0x29
RADAR_SPRITE_TORENORANCH = 0x2a
RADAR_SPRITE_TRIADS = 0x2b
RADAR_SPRITE_TRIADSCASINO = 0x2c
RADAR_SPRITE_TSHIRT = 0x2d
RADAR_SPRITE_WOOZIE = 0x2e
RADAR_SPRITE_ZERO = 0x2f
RADAR_SPRITE_DATEDISCO = 0x30
RADAR_SPRITE_DATEDRINK = 0x31
RADAR_SPRITE_DATEFOOD = 0x32
RADAR_SPRITE_TRUCK = 0x33
RADAR_SPRITE_CASH = 0x34
RADAR_SPRITE_FLAG = 0x35
RADAR_SPRITE_GYM = 0x36
RADAR_SPRITE_IMPOUND = 0x37
RADAR_SPRITE_LIGHT = 0x38
RADAR_SPRITE_RUNWAY = 0x39
RADAR_SPRITE_GANGB = 0x3a
RADAR_SPRITE_GANGP = 0x3b
RADAR_SPRITE_GANGY = 0x3c
RADAR_SPRITE_GANGN = 0x3d
RADAR_SPRITE_GANGG = 0x3e
RADAR_SPRITE_SPRAY = 0x3f
