user = "ARMOR"
version = "4.3.4"
last_push_time = 2024-07-18T02:06:14.185588Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: None _ZN11CFileLoader9LoadLevelEPKc(args=0); @0xfa9830 vars=0 len=0x8aa> from ARMOR"
