last_change = 2024-07-12T02:33:46.931434Z
name = "CAETwinLoopSoundEntity"
size = 0xb0

[members.0x0]
name = "audio"
offset = 0x0
type = "CAEAudioEntity"
size = 0x78

[members.0x78]
name = "m_wBankSlotId"
offset = 0x78
type = "short"
size = 0x2

[members.0x7a]
name = "m_wSoundType"
offset = 0x7a
type = "short[2]"
size = 0x4

[members.0x7e]
name = "_pad1"
offset = 0x7e
type = "char[2]"
size = 0x2

[members.0x80]
name = "m_pAudioEntity"
offset = 0x80
type = "CAEAudioEntity *"
size = 0x8

[members.0x88]
name = "field_88"
offset = 0x88
type = "_WORD"
size = 0x2

[members.0x8a]
name = "field_8A"
offset = 0x8a
type = "short"
size = 0x2

[members.0x8c]
name = "field_8C"
offset = 0x8c
type = "short"
size = 0x2

[members.0x8e]
name = "m_wPlayTimeMin"
offset = 0x8e
type = "short"
size = 0x2

[members.0x90]
name = "m_wPlayTimeMax"
offset = 0x90
type = "short"
size = 0x2

[members.0x92]
name = "_pad2"
offset = 0x92
type = "char[2]"
size = 0x2

[members.0x94]
name = "m_dwTimeToSwapSounds"
offset = 0x94
type = "int"
size = 0x4

[members.0x98]
name = "m_bPlayingFirstSound"
offset = 0x98
type = "char"
size = 0x1

[members.0x99]
name = "_pad3"
offset = 0x99
type = "char"
size = 0x1

[members.0x9a]
name = "m_wStartingPlayPercentage"
offset = 0x9a
type = "short[2]"
size = 0x4

[members.0x9e]
name = "field_9E"
offset = 0x9e
type = "short"
size = 0x2

[members.0xa0]
name = "m_apSounds"
offset = 0xa0
type = ""
size = 0x10
