last_change = 2024-07-18T01:58:18.051460Z
name = "CRunningScript"
size = 0x120

[members.0x0]
name = "pNext"
offset = 0x0
type = "CRunningScript *"
size = 0x8

[members.0x8]
name = "m_pPrev"
offset = 0x8
type = "CRunningScript *"
size = 0x8

[members.0x10]
name = "m_szName"
offset = 0x10
type = "char[8]"
size = 0x8

[members.0x18]
name = "m_pBaseIP"
offset = 0x18
type = "uint8_t *"
size = 0x8

[members.0x20]
name = "m_pCurrentIP"
offset = 0x20
type = "uint8_t *"
size = 0x8

[members.0x28]
name = "m_apStack"
offset = 0x28
type = "uint8_t *[8]"
size = 0x40

[members.0x68]
name = "m_nSP"
offset = 0x68
type = "uint16_t"
size = 0x2

[members.0x6c]
name = "m_aLocalVars"
offset = 0x6c
type = "int32_t[42]"
size = 0xa8

[members.0x114]
name = "m_bIsActive"
offset = 0x114
type = "uint8_t"
size = 0x1

[members.0x115]
name = "m_bCondResult"
offset = 0x115
type = "uint8_t"
size = 0x1

[members.0x116]
name = "m_bUseMissionCleanup"
offset = 0x116
type = "uint8_t"
size = 0x1

[members.0x117]
name = "m_bIsExternal"
offset = 0x117
type = "uint8_t"
size = 0x1

[members.0x118]
name = "m_bTextBlockOverride"
offset = 0x118
type = "uint8_t"
size = 0x1

[members.0x119]
name = "m_nScriptBrainType"
offset = 0x119
type = ""
size = 0x1
