last_change = 2024-07-18T01:58:18.022845Z
name = "CRunningScript"
size = 0x118

[members.0x0]
name = "pNext"
offset = 0x0
type = "CRunningScript *"
size = 0x8

[members.0x8]
name = "m_pPrev"
offset = 0x8
type = "CRunningScript *"
size = 0x8

[members.0x10]
name = "m_szName"
offset = 0x10
type = "char[8]"
size = 0x8

[members.0x18]
name = "m_pBaseIP"
offset = 0x18
type = "uint8_t *"
size = 0x8

[members.0x20]
name = "m_pCurrentIP"
offset = 0x20
type = "uint8_t *"
size = 0x8

[members.0x28]
name = "m_apStack"
offset = 0x28
type = "uint8_t *[8]"
size = 0x40

[members.0x68]
name = "m_nSP"
offset = 0x68
type = "uint16_t"
size = 0x2

[members.0x6c]
name = "m_aLocalVars"
offset = 0x6c
type = ""
size = 0xa8
